services:
  app:
    build:
      context: .
    ports:
      - "26032:26032"
    environment:
      - PORT=26032
      - NODE_ENV=production
      - FRONTEND_PORT=26031
      - FRONTEND_URL=http://127.0.0.1:26031
    restart: unless-stopped
